### ISSUE TITLE
Changes proposal

### ISSUE THREAD

**Issue by adibo** [dmirecki/pyMorfologik#1]
Hi,

Your module received mine interest. I would have a proposal for a couple of updates/changes, the main being:
1. make it Python2 compliant
2. change the way the output is generated; I propose not to have a dictionary, but rather a list of tuples, for example:
Morfologik().get_simple_stem(['Ala ma kota']), would return:
[('Ala', ['Ala', 'Al', 'Alo']),
 ('ma', ['mieć', 'mój'])
 ('kota', ['kota', 'kot', 'kot', 'kot'])]
3. Appropriate description changes 

In my opinion this should be more in line with the output of the original Morfologik. One could easily convert it to the way your original proposal defined it.

I have forked your repo and would made the necessary changes. Let me know if you are okey with the proposal. If yes, I would make a pull request, otherwise I'd stay in a separate repo to continue the development.
In any case, thanks for your work! ;)

BR,
Adrian

**Comment by dmirecki** [comment]
Thanks for your post!

I think that Python2 compatibility is very good idea. Sorry that I didn't care about Python2 earlier but pyMorfologik was a part of bigger application written in Python3.

I have an idea how to reconcile "list of tuples" with "dictionary". I propose to create an abstract class Parser with abstract method parse. Then create a method get_stem in Morfologik class, which expect 2 parameters: list of words and instance of parser. So get_stem method will look like:

```
def get_stem(self, words, parser):
    words = self._make_unique(words)
    output = self._run_morfologik(words)
    return parser.parse(output)
```

Thus you can create a "to list of tuples" parser extending abstract parser and we can accomodote existing code to "to dict" parser. Moreover I would like to create (in the near future) a parser which care about information like category of word (verb/adj/...), gender, etc. And naturally way to do it, will be just extend abstract parser and make some code.

What do you think about it?

Anyway, I think that pull request is good idea.

Damian

**Comment by adibo** [comment]
Hi!
(I realized we could discuss things in Polish, but I guess it's good to keep things readable for the rest of the world too)

Good idea!. I'll make the changes and submit it via a pull request soon. 

Yet there would be few minor changes from my side: 
1. to shift _make_unique() from within get_stem() of Morfologik class to a Parser class; 
For my application I would need all text to be stemmed, with some words repeating (and thus with repeating stems). So _make_unique() is not desired for my purposes. I hope that's okey (and it is in line with the morfologik way of outputing things anyway. Still, one could remove repeating words (and hence stems) in a parser if one wishes so, or by simply reducing (via set()?) a list of words supplied as an input
2. let's rename get_stem() to stem() => even simpler name; it is also a verb so it will play nicely here
3. let's add **kwargs to stem(), so some additional parameters could be used if needed

I'll submit my proposal soon.

Regards,
Adrian

**Comment by adibo** [comment]
Thanks for the merge. Wouldn't this be a good time to release a new pip package? 
I would say it would! :)
